### ISSUE TITLE
"/bin/sh: pkg-config: not found" on github workflows with ubuntu-latest

### ISSUE THREAD

**Issue by barbarbar338** [Automattic/node-canvas#1659]
## Issue or Feature 
Issue

## Steps to Reproduce
run build phase with this dockerfile
```dockerfile
FROM node:current-alpine
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \ 
    && yarn install \
    && apk del .gyp
COPY . .
RUN yarn run build
ENV PORT=8080
CMD [ "yarn", "run", "start:prod" ]
```
and this workflow
```yml
name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.6.1
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 14.9.0 on ubuntu-latest (github workflow)

I want to publish my project on fly.io and do a build with dockerfile. It says:
```
==> Validating App Configuration
--> Validating App Configuration done
Services
TCP 80/443 ⇢ 8080 

Deploy source directory '/github/workspace'
Docker daemon available, performing local build...
==> Building with Dockerfile
```
everything is okay but on yarn `[4/4] Building fresh packages...` phase, im encountering an error like this: https://paste.ee/p/qX7Ds
