### ISSUE TITLE
Request for arm64 Linux Prebuild Package

### ISSUE THREAD

**Issue by narukeu** [Automattic/node-canvas#2392]
## Issue or Feature
I am creating a Docker container for a Node.js project on an arm64 computer, which includes node-canvas. I believe there are many users with similar needs, so I hope you can provide an arm64 Linux prebuild package.

## Your Environment
Debian GNU/Linux arm64

**Comment by giacomo-bananadevs** [comment]
Does anyone managed to build the package from source? I can't find a way to build it on a windows ARM64 that runs WSL2. 
I need to install the package on the ubuntu subsystem, running: 
```
gyp info using **node-gyp@10.2.0**
gyp info using **node@20.10.0 | linux | arm64**
gyp info find Python using **Python version 3.10.12** found at "/usr/bin/python3"
```
Even trying to hand-compiling the package results always in the same error: 
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.10.0
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> ([path_top_home_dir]/.nvm/versions/node/v20.10.0/lib/node_modules/node-gyp/lib/build.js:216:23)
gyp ERR! **System Linux 5.15.153.1-microsoft-standard-WSL2**
gyp ERR! command "[path_top_home_dir]/.nvm/versions/node/v20.10.0/bin/node" "[path_top_home_dir]/.nvm/versions/node/v20.10.0/bin/node-gyp" "build"
gyp ERR! cwd [path_to_prj]/node_modules/canvas/build
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok
```

I there any workaround to installa the package on Ubuntu ARM64? Or am I missing something?

**Comment by cjutstraMaxedy** [comment]
This would also be very helpful for us. We're running automated tests on ARM machines.

**Comment by kadishmal** [comment]
From `.buildspec` for AWS CodeBuild:
```
version: 0.2
phases:
  install:
    commands:
      # We need to install node-canvas from source since there are no prebuilt libraries
      # for ARM64.
      # Install Canvas development dependencies to build from source code.
      - yum install -y gcc-c++ cairo-devel pango-devel libjpeg-turbo-devel giflib-devel
      - npm install
      # Copy dependency libraries to the package for bundling.
      - mkdir lib
      # Download and run the lddtree script to extract all dependencies.
      - curl https://raw.githubusercontent.com/ncopa/lddtree/v1.26/lddtree.sh -o lddtree.sh
      - chmod +x lddtree.sh
      - cp $(./lddtree.sh -l node_modules/canvas/build/Release/canvas.node | grep '^\/lib' | sed -r -e '/canvas.node$/d') lib/
      - ls lib/*
    runtime-versions:
      nodejs: 20
artifacts:
  exclude-paths:
    - ./coverage/**/*
    - ./node_modules/@types/**/*
    - ./node_modules/**/*.d.ts
    - ./__test__/**/*
  files:
    # Include production dependencies.
    - ./lib/*
    - ./node_modules/**/*
```
